apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub2
  labels:
    app: sub2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub2
  template:
    metadata:
      labels:
        app: sub2
    spec:
      containers:
        - name: sub2
          image: sub2:local
          imagePullPolicy: Never
          env:
            - name: BROKER_HOST
              value: "100.78.244.40"
            - name: BROKER_PORT
              value: "8080"
            - name: LOKI_URL
              value: "http://100.78.244.40:8091"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"