apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:8091
    isDefault: false

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: lab1
      defaultBucket: metrics
      httpMode: POST
    secureJsonData:
      token: "$__env{GF_INFLUXDB_TOKEN}"
    isDefault: true
